[0m[[0m[31merror[0m] [0m[0mjava.io.FileNotFoundException: log-generator.log (Le fichier sp√©cifi√© est introuvable)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.io.FileInputStream.open0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.io.FileInputStream.open(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.io.FileInputStream.<init>(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.io.Source$.fromFile(Source.scala:94)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.io.Source$.fromFile(Source.scala:79)[0m
[0m[[0m[31merror[0m] [0m[0m	at LogFileAnalyzer$.main(Main.scala:27)[0m
[0m[[0m[31merror[0m] [0m[0m	at LogFileAnalyzer.main(Main.scala)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.lang.reflect.Method.invoke(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.invokeMain(Run.scala:143)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.execute$1(Run.scala:93)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$$Lambda$5719/395907272.apply$mcV$sp(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run$.executeSuccess(Run.scala:186)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Run.runWithLoader(Run.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1980)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$$$Lambda$5713/372773041.apply$mcV$sp(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1919)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.Defaults$$$Lambda$5714/1141816783.apply$mcV$sp(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.util.Try$.apply(Try.scala:213)[0m
[0m[[0m[31merror[0m] [0m[0m	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m	at java.lang.Thread.run(Unknown Source)[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mrun[0m) java.io.FileNotFoundException: log-generator.log (Le fichier sp√©cifi√© est introuvable)[0m
